language: cpp

compiler:
 - gcc
 - clang

env:
  - CXX11=true TARGET=build_osrm_for_linux
  - CXX11=false TARGET=build_osrm_for_linux
  - CXX11=true TARGET=build_mapnik_for_linux
  - CXX11=false TARGET=build_mapnik_for_linux

before_install:
 # fixes node/gyp install
 # https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
 - true

before_script:
 - true

script:
 - source ./build.sh
 - ${TARGET}