language: objective-c

compiler:
 - clang

before_install:
 - true

env:
  - CXX11=true TARGET=build_for_osx
  - CXX11=false TARGET=build_for_osx

before_install:
  - true

install:
 - true

before_script:
 - cd osx
 - export CXX11=true
 - source MacOSX.sh

script:
 - source ./build.sh
 - ${TARGET}

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
