language: objective-c

compiler:
 - clang

env:
  - CXX11=true TARGET=build_for_osx
  - CXX11=false TARGET=build_for_osx

before_install:
 # fixes node/gyp install
 # https://github.com/travis-ci/travis-cookbooks/issues/155
 #- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
 - true

before_script:
 - true

script:
 - source ./build.sh
 - ${TARGET}

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true