language: cpp

compiler:
 - gcc

env:
  - CXX11=false
  - CXX11=true

before_install:
 - if [ "${CXX11}" = true ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
 - sudo apt-get update -y
 - apt-get install -y build-essential git unzip python-dev libbz2-dev

before_install:
 # upgrade compilers
 - if [ "${CXX11}" = true ]; then sudo apt-get install -y gcc-4.7 g++-4.7; fi;

install:
 - cd osx
 - source Linux64.sh
 - if [ "${CXX11}" = true ]; then export CC=gcc-4.7 && export CXX=g++-4.7; fi;
 - ./scripts/download_deps.sh
 - ./scripts/build_core_deps.sh
 - ./scripts/build_deps_optional.sh
 - ./scripts/build_python_versions.sh
 - ./scripts/build_protobuf.sh

before_script:
 - true

script:
 - true

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
