language: objective-c

compiler:
 - clang

before_install:
 - true

install:
 - true

before_script:
 - cd osx
 - export CXX11=true
 - source MacOSX.sh

script:
 - ./scripts/download_deps.sh
 - ./scripts/build_core_deps.sh
 - ./scripts/build_protobuf.sh
 - ./scripts/build_node.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
